### ISSUE TITLE
Reusable setup hook

### ISSUE THREAD

**Issue by sibbngheid** [antfu/reactivue#1]
I'm not sure is this currently possible but if it is not [zustand](https://github.com/react-spring/zustand) like api would be awesome for global state.

**Comment by antfu** [comment]
Yeah I think you can. Libraries like this https://github.com/posva/pinia/tree/next should work if you aliasing `vue` to `reactivue`. I can try and make an example i guess

**Comment by sibbngheid** [comment]
I don't like pinia's api. It is feels like vuex. I would like to use composition api. For example:

```ts
import React from 'React'
import { createSetup, ref, computed, onUnmounted } from 'reactivue'

interface Props {
  value: number
}

const [useSetup] = createSetup(
  (props: Props) => { // props is a reactive object in Vue
    const counter = ref(props.value)
    const doubled = computed(() => counter.value * 2)
    const inc = () => counter.value += 1

    onUnmounted(() => console.log('Goodbye World'))

    return { counter, doubled, inc }
  }
)

function MyCounter(Props: Props) {
  const { counter, doubled, inc } = useSetup(Props)

  return (
    <div>
      <div>{counter} x 2 = {doubled}</div>
      <button onClick={inc}>Increase</button>
    </div>
  )
}
```

**Comment by antfu** [comment]
Emm anyway, it works https://github.com/antfu/reactivue/commit/2019bf5afc6562e392aa77a3ec8859d9ba593c00. So I think you can make your own easily :)

**Comment by antfu** [comment]
@sibbngheid Rethought about your proposal and I think it's good to have! Will implement it soon.

**Comment by sibbngheid** [comment]
Maybe an edge case:

I'm expecting `useSetup `will return shared state across all calls like zustand. But I'm passing props to my hook instead of selecting state unlike zustand. So, what happens if i call useSetup hook in multiple components with different props?

It is should not return new state instance. Because [current api](https://github.com/antfu/reactivue#hooks) is already capable to do that by simply extracting setup function.

There is two way:
 It is can ignore the props after the first call. 
Or overwrite the state.

I don't know which one is better for real use cases. Creating a store instance based on component puts my proposal to different place than zustand. 

Maybe we don't even need to pass props to resusable hook. Simply using functions to mutate shared state is would be enough.

**Comment by sibbngheid** [comment]
My final thoughs:
> Simply using functions to mutate shared state is would be enough.
This should be the expecting way to work with reusable hooks.
> Or overwrite the state.
Passing props is optional. If it is used, must overwrite the state.

Here it is example which also uses current api:

```
import React from 'React'
import { createSetup, useSetup ref } from 'reactivue'

const useSharedCounter = createSetup(
  (start = 0) => { // start paramter is optional with default value
    const counter = ref(start)
    const inc = () => counter.value += 1

    return { counter, inc }
  }
)

function MyCounter(props) {
  const { counter, inc } = useSharedCounter(props.start)

  return (
    <div>
      <div>Counter: {counter}</div>
      <button onClick={inc}>Increase</button>
    </div>
  )
}

function App() {
  const { visible, toggle } = useSetup(() => {
    const visible = ref(false)
    const toggle = () => visible.value = !visible.value

    return {visible, toggle}
  })

  return (
    <>
      <MyCounter />
      {visible && <MyCounter start="10" />}
      <button onClick={toggle}>Toggle second counter</button>
    </>
  )
}

```

When second counter becomes visible, should overwrite shared state and first counter should reflect changes.

**Comment by antfu** [comment]
Guess you are thinking about it in the wrong direction. If you need a global state, you can already do that Vue's level.

```ts
const GlobalState = reactive({ ... })

function App() {
  const state = useSetup(() => GlobalState)
  
  // ...
}
```

or 
   
```ts
const GlobalState = reactive({ ... })
const useState = createSetup(() => GlobalState)

function App() {
  const state = useState()
  
  // ...
}
```

**Comment by sibbngheid** [comment]
Ok, I figured out it. Simply defining refs outside of setup function and returning them on setup functions works as well. Actually im working on global states on my vue3+vite app like that. I think focusing on zustand api so much caused me to go wrong direction.

Good work, keep it up 👍✌😊

Fixed in https://github.com/antfu/reactivue/pull/3
