### ISSUE TITLE
SetupFunction wants not to return the value

### ISSUE THREAD

**Issue by yi-tuan** [antfu/reactivue#30]
When you use `defineComponent`, the first function argument that does not return any value will throw an error, hopefully `setupFunction` will be compatible with not returning any value or provide a friendlier hint to developers

![image](https://user-images.githubusercontent.com/32629463/108802575-ab743100-75d3-11eb-9bd0-94b743058ca2.png)

**Comment by antfu** [comment]
Can you provide more context? Thanks

**Comment by yi-tuan** [comment]
> Can you provide more context? Thanks

have updated

**Comment by antfu** [comment]
Ehmm, can you share some code snippets that causes this problem?

**Comment by yi-tuan** [comment]
like this
![image](https://user-images.githubusercontent.com/32629463/108819013-36195800-75f5-11eb-9df5-affd21501a35.png)
