### ISSUE TITLE
Got error when using Pinia: Uncaught SyntaxError: import not found: effectScope

### ISSUE THREAD

**Issue by keith0305** [antfu/reactivue#48]
As of Pinia 2.0.0, the use of effectScope was introduced, hence I believe is the reason why I got this error.

If I remove the following code from `vite.config.js`, the error would go away.
```js
alias: {
    'vue': 'reactivue',
    '@vue/runtime-dom': 'reactivue',
  },
```

This is probably due to `"vue": "^3.2.31"` in `package.json`.
However, I lose reactivity in React component this way.

Edit:
Pinia changelog for 2.0.0-rc.0 here:
https://github.com/vuejs/pinia/blob/v2/packages/pinia/CHANGELOG.md#200-rc0-2021-07-28=

And documentation for effectScope here:
https://vuejs.org/api/reactivity-advanced.html#effectscope

**Comment by sibbng** [comment]
Vue 3.2+ support is currently in beta. Check #46 for details. One of the biggest change in beta version is you need to remove aliases and import composition apis directly from vue. Check playgrounds folder in [next ](https://github.com/antfu/reactivue/tree/next) branch for examples.

**Comment by keith0305** [comment]
Thanks for the info! I am closing this now.
