### ISSUE TITLE
pinia integration not working: effectScope not found in 'vue-demi'

### ISSUE THREAD

**Issue by andrei-gheorghiu** [antfu/reactivue#51]
Trying to integrate in the following setup:
```
   dependencies: {
     "pinia": "^2.0.12",
     "react": "^18.0.0",
     "reactivue": "^0.4.4",
   }
```
(which, at the point of posting is latest stable from each).

Getting the following `ERROR in ./node_modules/pinia/dist/pinia.esm-browser.js 991:16-27`:

`export 'effectScope' (imported as 'effectScope') was not found in 'vue-demi'`

I know it's coming from `pinia` but thought I'd ask here first, in case others might have run into it.
___
On the same note, it would be good if you posted an example, to know in which version combos this works.

Thanks.

**Comment by sibbng** [comment]
`effectScope` support is available in beta version. Check https://github.com/antfu/reactivue/issues/48 for more details.
