### ISSUE TITLE
Make 'useSetup' second argument and createSetup argument optional. 

### ISSUE THREAD

**Issue by Dav3rs** [antfu/reactivue#6]
Hi, a little thing, If I have a component with no props, then I don't have a prop argument for the useSetup, but typescript is requiring it and I use an empty object instead. And the same for 'createSetup', It is forcing me to give it an empty object or something.

**Comment by antfu** [comment]
Make sense. Would you mind to send a PR? Thanks

**Comment by antfu** [comment]
Thanks!
