### ISSUE TITLE
项目不更新了？

### ISSUE THREAD

**Issue by agileago** [antfu/reactivue#64]
### Describe the bug

-

### Reproduction

https://github.com/agileago/fe-template

### System Info

```Shell
-
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agileago** [comment]
@sibbng

**Comment by sibbng** [comment]
This repository is not up to date.

If you are looking for ways to use Vue composables in React, I would suggest you use [effectScope](https://vuejs.org/api/reactivity-advanced.html#effectscope).

**Comment by CJY0208** [comment]
@sibbng I noticed that the next branch in this git repository has been rewritten using `effectScope`, but a stable version has not been released. Did you encounter any issues?

I have also experimented with the effectScope approach, implementing basic syntax injection for the `composition-api`, `hmr` support, and lifecycle features. However, I am still uncertain about the value of this direction and would like to know more about the problems you have encountered.

I really like this library, as it helps me solve many issues inherent to React Hooks. If there is significant progress, I would like to get involved in maintaining the current library. Do you have any advice for me?
