### ISSUE TITLE
Add Integration Tests

### ISSUE THREAD

**Issue by crutchcorn** [antfu/reactivue#9]
Hello! 👋  I love the work you've been doing on this project. In fact, it inspired me (and the code therewithin 😅  - I plan on giving more credit than I am currently when I write more docs) to write an Angular alternative [`ngx-vue`](https://github.com/oceanbit-dev/ngx-vue) that I'm actively working on.

One of the things I'm working on with this library is tests using the [Angular Testing Library](https://testing-library.com/docs/angular-testing-library/intro/) to make sure that nothing is broken between releases and that everything works as-expected.

[Here's an example of some of the tests I'm writing](https://github.com/oceanbit-dev/ngx-vue/blob/remove-decorator/projects/ngx-vue/src/lib/setup.test.ts)

While looking at `reactivue` to see if there were any tests like this, I was surprised to find that there weren't. I would love to contribute tests using the [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/). Would this be a welcome contribution?

Thanks so much yet again for this awesome library.

**Comment by antfu** [comment]
As you probably know I am more like a Vue guy and I am that expertise in React (and TBH I am not actually using this lib myself recently). But really happy to see someone find this lib useful and inspiring, thank you! And that would be awesome if you are interested in setting up the tests or even help on improving this project :)
